version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: psicosst
      POSTGRES_PASSWORD: psicosst
      POSTGRES_DB: psicosst
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://psicosst:psicosst@db:5432/psicosst
      JWT_SECRET: supersecreto
      S3_BUCKET: psicosst-bucket
      S3_REGION: us-east-1
      S3_ACCESS_KEY: tu_access_key
      S3_SECRET_KEY: tu_secret_key
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./storage:/app/storage
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:4000
